package guiwithobservabledesignpattern;

import java.awt.Image;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import javax.swing.ImageIcon;

/**
 * import project.ClientPriceObserver;
 *
 *
 * @author Ahmed El-Torky
 */
public class GUIClient extends javax.swing.JFrame {

    private static final int GET_CHECKOUT_REQ = -1;
    private static final int GET_PRICE_REQ = -2;
    private Socket clientSocket;
    private DataOutputStream dosCS;
    private DataInputStream disCS;
    private Thread t1;
    private Image apple = new ImageIcon("apple.png").getImage();
    private Image banana = new ImageIcon("banana.jpg").getImage();
    private Image orange = new ImageIcon("orange.jpg").getImage();

    /**
     * Creates new form Client
     */
    public GUIClient() {
        initComponents();
        this.startConnection();
        this.getPricesFromServer();
        appleImage.setIcon(new ImageIcon(apple));
        bananaImage.setIcon(new ImageIcon(banana));
        orangeImage.setIcon(new ImageIcon(orange));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appleImage = new javax.swing.JLabel();
        bananaImage = new javax.swing.JLabel();
        orangeImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        applePriceLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bananaPriceLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        orangePriceLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        appleQty = new javax.swing.JSpinner();
        bananaQty = new javax.swing.JSpinner();
        orangeQty = new javax.swing.JSpinner();
        checkout = new javax.swing.JButton();
        priceLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Electronic Grocery Shop");
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Apple");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        applePriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        applePriceLabel.setText("?? LE/Kg");
        applePriceLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Banana");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bananaPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bananaPriceLabel.setText("?? LE/Kg");
        bananaPriceLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Orange");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        orangePriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orangePriceLabel.setText("?? LE/Kg");
        orangePriceLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Qty:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Qty:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Qty");

        appleQty.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        bananaQty.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        orangeQty.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        checkout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkout.setText("Checkout");
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });

        priceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        priceLabel.setText("Total Price = ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(applePriceLabel)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(appleQty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bananaPriceLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bananaQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orangePriceLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orangeQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(appleImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkout)
                                .addGap(18, 18, 18)
                                .addComponent(priceLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bananaImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(orangeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {appleImage, bananaImage, orangeImage});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {applePriceLabel, bananaPriceLabel, jLabel1, jLabel3, jLabel5, orangePriceLabel});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel7, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {checkout, priceLabel});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {appleQty, bananaQty, orangeQty});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appleImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bananaImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orangeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applePriceLabel)
                    .addComponent(bananaPriceLabel)
                    .addComponent(orangePriceLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(appleQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bananaQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orangeQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkout)
                    .addComponent(priceLabel))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {appleImage, bananaImage, orangeImage});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {applePriceLabel, bananaPriceLabel, jLabel1, jLabel3, jLabel5, orangePriceLabel});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel7, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {checkout, priceLabel});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {appleQty, bananaQty, orangeQty});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
        this.getTotalPrice();
    }//GEN-LAST:event_checkoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appleImage;
    private javax.swing.JLabel applePriceLabel;
    private javax.swing.JSpinner appleQty;
    private javax.swing.JLabel bananaImage;
    private javax.swing.JLabel bananaPriceLabel;
    private javax.swing.JSpinner bananaQty;
    private javax.swing.JButton checkout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel orangeImage;
    private javax.swing.JLabel orangePriceLabel;
    private javax.swing.JSpinner orangeQty;
    private javax.swing.JLabel priceLabel;
    // End of variables declaration//GEN-END:variables

    private void startConnection() {
        try {
            clientSocket = new Socket("localhost", 1991);
            dosCS = new DataOutputStream(clientSocket.getOutputStream());
            disCS = new DataInputStream(clientSocket.getInputStream());

            t1 = new Thread(new ClientPriceObserver(this, disCS));
            t1.start();
        } catch (IOException ex) {
            System.out.println(ex.toString());
        }
    }

    private void getTotalPrice() {
        try {
            dosCS.writeInt(GET_CHECKOUT_REQ);
            dosCS.writeInt((Integer) appleQty.getValue());
            dosCS.writeInt((Integer) bananaQty.getValue());
            dosCS.writeInt((Integer) orangeQty.getValue());

//            dosCS.close();
//            disCS.close();
//            clientSocket.close();
        } catch (IOException ex) {
            System.out.println(ex.toString());
        }
    }

    public void setTotalPriceLable(int totalPrice) {
        priceLabel.setText(String.valueOf("Total Price = " + totalPrice + " £"));
    }

    private void getPricesFromServer() {
        try {
            dosCS.writeInt(GET_PRICE_REQ);
        } catch (IOException ex) {
            System.out.println(ex.toString());
        }
    }

    public void setPrices(int applePrice, int bananaPrice, int orangePrice) {
        applePriceLabel.setText(String.valueOf(applePrice) + " LE/Kg");
        bananaPriceLabel.setText(String.valueOf(bananaPrice) + " LE/Kg");
        orangePriceLabel.setText(String.valueOf(orangePrice) + " LE/Kg");
    }
}
